### ISSUE TITLE
Moving friction and Rolling friction 

### ISSUE THREAD

**Issue by chardian** [tailuge/billiards#44]
in constants.ts

export const mu = 0.8

But,  Moving friction is much larger  than Rolling friction

It should not be one variable.

**Comment by tailuge** [comment]
I agree we could have separate coefficient of friction for sliding and rolling. The current code is based around:

https://billiards.colostate.edu/physics_articles/Han_paper.pdf

In that paper the rolling friction is related to the sliding friction by equation 8
That is in the code as:

export const Mxy = (7 / (5 * Math.sqrt(2))) * mu * m * g * 0.25

When I tried this without the 0.25 scaling factor the simulation did not feel realistic. I am open to having direct constant for Mxy if you know suitable values.

Diagrams are useful in choosing the values:

http://tailuge.github.io/billiards/dist/diagrams.html

**Comment by chardian** [comment]
OK, thanks a lot!
I have already read the paper , and derived the formula about velocity and angle-velocity myself, but I just ignore the 0.25 



Now I have an other question,

In physics.ts, line 9 - line 11

export function surfaceVelocityFull(v, w) {
  return v.clone().add(upCross(w))
}


I think it should be

export function surfaceVelocityFull(v, w) {
  return v.clone().add(upCross(w)  *  R)    // Because R = 0.5  instead of 1.0
}

**Comment by tailuge** [comment]
I think you are correct since v=rw.

I cannot update the code directly now e.g.

export function surfaceVelocityFull(v, w) {
  return v.clone().addScaledVector(upCross(w),R)
}

because I think this confusion of R=0.5 or R=1 occurs frequently throughout the code. I aim to fix this when I've found all places where this impacts.

**Comment by tailuge** [comment]
Take a look at

https://github.com/tailuge/billiards/commit/19614e6732ce254d1199beab4dcf21b1ef90a0b6

I have made the equations match the paper directly with inclusion of R throughout. 

The ball behaviour is about the same but I have now removed the odd 0.25 constant that was used earlier and mu is now 0.2 matching other papers values.
